In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Challenge_GIN_release_profile_17804library_181query.txt",delimiter='\t',engine='python',index_col=0)
df.to_csv
df

gene2     gene4     gene5     gene6     gene7     gene9    gene10  \
gene1  -0.112264 -0.082520 -0.023137  0.182967  0.074300 -0.123003 -0.085812   
gene2   0.065839 -0.118887 -0.005756  0.023376 -0.029996 -0.223476 -0.528847   
gene3  -0.182295  0.025287  0.085027 -0.760465 -0.402773  0.571947  0.198041   
gene4   0.029526  0.984989 -0.491993 -0.823344 -0.234515  0.036838  0.483608   
gene5   0.033636 -2.167970  0.633415 -0.482965 -0.192736  0.210778  0.301757   
...          ...       ...       ...       ...       ...       ...       ...   
BRAT1  -0.117455  0.027633 -0.014888 -0.007351 -0.252038  0.119898  0.134670   
AFF3    0.042818  0.040710  0.101488  0.038266 -0.152184 -0.076716 -0.379674   
U2SURP -0.052811  0.374745  0.082581 -0.047819  0.044962  0.110566  0.277545   
ZMAT2  -0.054411  0.223394 -0.132306  0.084143 -0.172811  0.088873 -0.053579   
MS4A13 -0.132750  0.133087 -0.032397  0.015513  0.064933  0.050284 -0.256850   

          gene11    gene12    gene14  ...   gene210   gene211   gene212  \
gene1  -0.066072 -0.074032 -0.289072  ...  0.101428 -0.130816  0.129142   
gene2  -0.125624 -0.452441  0.065494  ... -0.063921  0.158165 -0.302828   
gene3   0.324254 -0.748180  0.015663  ... -1.328485 -0.194828  0.362047   
gene4   0.611454  0.376156  0.029306  ...  0.107450 -0.292311 -0.626240   
gene5   0.406734  0.218177  0.175707  ...  0.182165 -0.205287 -0.639710   
...          ...       ...       ...  ...       ...       ...       ...   
BRAT1  -0.010432 -0.299120  0.024199  ... -0.084588 -0.154024  0.066592   
AFF3   -0.231326 -0.225197  0.138000  ... -0.122220 -0.113323 -0.211457   
U2SURP  0.114996  0.211252 -0.055827  ... -0.170706 -0.158339  0.146913   
ZMAT2  -0.023604 -0.033867  0.160862  ...  0.082234  0.235284  0.529912   
MS4A13 -0.091959 -0.163776 -0.103803  ... -0.036812  0.199203  0.068985   

         gene213   gene214   gene215   gene217   gene218   gene220   gene221  
gene1   0.164773  0.222201  0.106131 -0.180773 -0.012366 -0.009747 -0.154899  
gene2  -0.320000 -0.031677  0.395132  0.123037  0.110232  0.101665  0.257199  
gene3   0.585154  0.141589  0.017662  0.035308 -0.128555  0.034865  0.047448  
gene4  -0.073600 -0.394079  0.076723  0.053355 -0.083475  0.497633  0.043747  
gene5   0.003630 -0.512942  0.184551 -0.068344  0.164594  0.551412  0.173682  
...          ...       ...       ...       ...       ...       ...       ...  
BRAT1   0.497428 -0.372607 -1.328724  0.006734  0.272284  0.139901  0.350091  
AFF3   -0.055832 -0.345783 -0.180888  0.133308 -0.340802 -0.299686  0.111915  
U2SURP  0.128541  0.005456  0.091263 -0.095923 -0.012799  0.065157  0.386429  
ZMAT2   0.153064 -0.215954 -0.216660  0.045671  0.104535  0.057949  0.035097  
MS4A13  0.270296 -0.119894 -0.275503  0.233243  0.181788  0.114834 -0.056764  

[17804 rows x 181 columns]

In [3]:
df.shape

(17804, 181)

In [4]:
list=df.columns.tolist()


In [5]:
df_select = df.loc[list]
df_select

gene2     gene4     gene5     gene6     gene7     gene9    gene10  \
gene2    0.065839 -0.118887 -0.005756  0.023376 -0.029996 -0.223476 -0.528847   
gene4    0.029526  0.984989 -0.491993 -0.823344 -0.234515  0.036838  0.483608   
gene5    0.033636 -2.167970  0.633415 -0.482965 -0.192736  0.210778  0.301757   
gene6    0.108013 -0.328879  0.162317  0.431703 -0.086004 -0.129172 -0.092746   
gene7    0.019646 -0.371370  0.071836 -0.041403  0.512223 -0.223488  0.350104   
...           ...       ...       ...       ...       ...       ...       ...   
gene215 -0.463643  0.082758  0.317132  0.161844 -0.036863 -0.002925  0.029971   
gene217  0.418748 -0.058076 -0.136244  0.109349  0.146626 -0.382758 -0.074248   
gene218 -0.322669 -0.308605  0.047688  0.051777 -0.029663 -0.385610 -0.204980   
gene220 -0.052638 -0.177903 -0.049280  0.047704  0.515500  0.101023  0.251072   
gene221 -0.067347  0.377201 -0.320437  0.229495 -0.070635  0.085685 -0.010330   

           gene11    gene12    gene14  ...   gene210   gene211   gene212  \
gene2   -0.125624 -0.452441  0.065494  ... -0.063921  0.158165 -0.302828   
gene4    0.611454  0.376156  0.029306  ...  0.107450 -0.292311 -0.626240   
gene5    0.406734  0.218177  0.175707  ...  0.182165 -0.205287 -0.639710   
gene6   -0.037032 -0.091183 -0.183854  ...  0.098941 -0.002686  0.305216   
gene7    0.130423  0.744391  0.305899  ... -0.007832 -0.043968 -0.024252   
...           ...       ...       ...  ...       ...       ...       ...   
gene215  0.016223 -0.397910  0.217715  ... -0.161846 -0.314271  0.139246   
gene217  0.100994 -0.042505 -0.082459  ... -0.118175 -0.271400  0.276619   
gene218  0.236129 -0.012021  0.031613  ... -0.067217  0.039918 -0.096817   
gene220 -0.123151 -0.344285 -0.186162  ...  0.055105  0.447805 -0.120764   
gene221  0.026625 -0.749728 -0.353951  ...  0.181114  0.050261 -0.602545   

          gene213   gene214   gene215   gene217   gene218   gene220   gene221  
gene2   -0.320000 -0.031677  0.395132  0.123037  0.110232  0.101665  0.257199  
gene4   -0.073600 -0.394079  0.076723  0.053355 -0.083475  0.497633  0.043747  
gene5    0.003630 -0.512942  0.184551 -0.068344  0.164594  0.551412  0.173682  
gene6   -0.218668 -0.199505  0.113797  0.010453 -0.072276 -0.210557  0.128117  
gene7   -0.273954 -0.113345  0.019182  0.158748 -0.145833 -0.147716  0.057948  
...           ...       ...       ...       ...       ...       ...       ...  
gene215  0.312857 -0.430084 -0.484038 -0.432958 -0.339392 -0.133166  0.076858  
gene217 -0.032658  0.130579 -0.246864  0.236280 -0.121157 -0.063129  0.108336  
gene218  0.014080 -0.098842 -0.391419  0.145380  0.474187  0.074106 -0.220055  
gene220  0.383497  0.340230 -0.265943 -0.169058 -0.050695  0.297601 -0.891525  
gene221 -0.635713  0.501333  0.116678  0.007682  0.562977 -0.311194  0.923732  

[181 rows x 181 columns]

In [6]:
test_df=pd.read_csv("ChallengeB_release_hold_out_40_query_genes.txt",delimiter='\t',engine='python',index_col=0)
test_df.to_csv
test_df=test_df.reset_index()
test_genes=test_df["hold_out_query_genes"].astype("string")
test_genes.head()

0    gene194
1     gene20
2     gene82
3     gene49
4     gene64
Name: hold_out_query_genes, dtype: string

In [7]:
# gene_feature=df.transpose().to_dict(orient="records")

In [8]:
# (181 X 181)
matrix=df_select.values
matrix

array([[ 0.06583944, -0.11888742, -0.00575577, ...,  0.11023176,
         0.1016647 ,  0.2571986 ],
       [ 0.02952638,  0.98498897, -0.49199274, ..., -0.08347453,
         0.49763344,  0.04374663],
       [ 0.03363636, -2.16797019,  0.6334151 , ...,  0.16459392,
         0.5514122 ,  0.17368199],
       ...,
       [-0.32266876, -0.30860534,  0.04768813, ...,  0.47418673,
         0.07410606, -0.22005477],
       [-0.05263766, -0.17790281, -0.04928005, ..., -0.05069485,
         0.29760144, -0.89152526],
       [-0.06734736,  0.37720076, -0.32043717, ...,  0.56297747,
        -0.31119432,  0.92373218]])

In [9]:
from sklearn.neural_network import MLPClassifier

In [10]:
df

gene2     gene4     gene5     gene6     gene7     gene9    gene10  \
gene1  -0.112264 -0.082520 -0.023137  0.182967  0.074300 -0.123003 -0.085812   
gene2   0.065839 -0.118887 -0.005756  0.023376 -0.029996 -0.223476 -0.528847   
gene3  -0.182295  0.025287  0.085027 -0.760465 -0.402773  0.571947  0.198041   
gene4   0.029526  0.984989 -0.491993 -0.823344 -0.234515  0.036838  0.483608   
gene5   0.033636 -2.167970  0.633415 -0.482965 -0.192736  0.210778  0.301757   
...          ...       ...       ...       ...       ...       ...       ...   
BRAT1  -0.117455  0.027633 -0.014888 -0.007351 -0.252038  0.119898  0.134670   
AFF3    0.042818  0.040710  0.101488  0.038266 -0.152184 -0.076716 -0.379674   
U2SURP -0.052811  0.374745  0.082581 -0.047819  0.044962  0.110566  0.277545   
ZMAT2  -0.054411  0.223394 -0.132306  0.084143 -0.172811  0.088873 -0.053579   
MS4A13 -0.132750  0.133087 -0.032397  0.015513  0.064933  0.050284 -0.256850   

          gene11    gene12    gene14  ...   gene210   gene211   gene212  \
gene1  -0.066072 -0.074032 -0.289072  ...  0.101428 -0.130816  0.129142   
gene2  -0.125624 -0.452441  0.065494  ... -0.063921  0.158165 -0.302828   
gene3   0.324254 -0.748180  0.015663  ... -1.328485 -0.194828  0.362047   
gene4   0.611454  0.376156  0.029306  ...  0.107450 -0.292311 -0.626240   
gene5   0.406734  0.218177  0.175707  ...  0.182165 -0.205287 -0.639710   
...          ...       ...       ...  ...       ...       ...       ...   
BRAT1  -0.010432 -0.299120  0.024199  ... -0.084588 -0.154024  0.066592   
AFF3   -0.231326 -0.225197  0.138000  ... -0.122220 -0.113323 -0.211457   
U2SURP  0.114996  0.211252 -0.055827  ... -0.170706 -0.158339  0.146913   
ZMAT2  -0.023604 -0.033867  0.160862  ...  0.082234  0.235284  0.529912   
MS4A13 -0.091959 -0.163776 -0.103803  ... -0.036812  0.199203  0.068985   

         gene213   gene214   gene215   gene217   gene218   gene220   gene221  
gene1   0.164773  0.222201  0.106131 -0.180773 -0.012366 -0.009747 -0.154899  
gene2  -0.320000 -0.031677  0.395132  0.123037  0.110232  0.101665  0.257199  
gene3   0.585154  0.141589  0.017662  0.035308 -0.128555  0.034865  0.047448  
gene4  -0.073600 -0.394079  0.076723  0.053355 -0.083475  0.497633  0.043747  
gene5   0.003630 -0.512942  0.184551 -0.068344  0.164594  0.551412  0.173682  
...          ...       ...       ...       ...       ...       ...       ...  
BRAT1   0.497428 -0.372607 -1.328724  0.006734  0.272284  0.139901  0.350091  
AFF3   -0.055832 -0.345783 -0.180888  0.133308 -0.340802 -0.299686  0.111915  
U2SURP  0.128541  0.005456  0.091263 -0.095923 -0.012799  0.065157  0.386429  
ZMAT2   0.153064 -0.215954 -0.216660  0.045671  0.104535  0.057949  0.035097  
MS4A13  0.270296 -0.119894 -0.275503  0.233243  0.181788  0.114834 -0.056764  

[17804 rows x 181 columns]

In [11]:
target=df.T

In [12]:
target.shape
target=target.values

In [13]:
#[180 x 181]---180 samples
train_input= matrix[:181,:].T

In [14]:
train_input.shape

(181, 181)

In [15]:
#[1 x 181] the last gene- gene221
test_input =matrix[-1]

In [16]:
test_input.shape

(181,)

In [17]:
#[17k x 180] gene2 - gene220
train_output=target[:181]

In [18]:
train_output= train_output.T

In [19]:
train_output.shape

(17804, 181)

In [20]:
#[17k x 1] gene221
test_output=target[180].T

In [21]:
test_output.shape

(17804,)

In [22]:
test_output

array([-0.15489869,  0.2571986 ,  0.04744789, ...,  0.38642932,
        0.03509739, -0.05676414])

In [23]:
test_input

array([-0.06734736,  0.37720076, -0.32043717,  0.22949494, -0.07063468,
        0.08568453, -0.01033034,  0.02662501, -0.74972814, -0.35395083,
        0.05519001, -0.18411949,  0.47778984, -0.49634217,  0.10356527,
        0.54863333,  0.0927815 ,  0.67791496, -0.11740533,  0.30076781,
        0.62233791,  0.35303102, -0.0347213 ,  0.16577196, -0.41175395,
       -0.24524938, -0.21148208,  0.59145201,  0.55549472, -0.47601274,
       -0.29538188,  0.10517921, -0.17181172, -0.1424821 ,  0.86323961,
        0.27799646, -0.08707307, -0.13300497, -0.91264594, -0.33123976,
        0.67667852, -0.24923448,  0.15306131, -0.57040785, -0.16803317,
       -0.06988018, -0.01668089, -0.03027854,  0.3470183 ,  0.32377689,
        0.19637731,  0.04703603, -0.07836217,  0.17098327, -0.32774848,
       -1.0198035 ,  0.13388713,  0.49893245, -0.27062952, -0.06541604,
        0.6114256 , -0.17649879, -0.16230428,  0.05497091, -0.45992752,
       -0.39104898, -0.00613514, -0.6005063 , -0.37695609, -0.66

In [24]:
df


gene2     gene4     gene5     gene6     gene7     gene9    gene10  \
gene1  -0.112264 -0.082520 -0.023137  0.182967  0.074300 -0.123003 -0.085812   
gene2   0.065839 -0.118887 -0.005756  0.023376 -0.029996 -0.223476 -0.528847   
gene3  -0.182295  0.025287  0.085027 -0.760465 -0.402773  0.571947  0.198041   
gene4   0.029526  0.984989 -0.491993 -0.823344 -0.234515  0.036838  0.483608   
gene5   0.033636 -2.167970  0.633415 -0.482965 -0.192736  0.210778  0.301757   
...          ...       ...       ...       ...       ...       ...       ...   
BRAT1  -0.117455  0.027633 -0.014888 -0.007351 -0.252038  0.119898  0.134670   
AFF3    0.042818  0.040710  0.101488  0.038266 -0.152184 -0.076716 -0.379674   
U2SURP -0.052811  0.374745  0.082581 -0.047819  0.044962  0.110566  0.277545   
ZMAT2  -0.054411  0.223394 -0.132306  0.084143 -0.172811  0.088873 -0.053579   
MS4A13 -0.132750  0.133087 -0.032397  0.015513  0.064933  0.050284 -0.256850   

          gene11    gene12    gene14  ...   gene210   gene211   gene212  \
gene1  -0.066072 -0.074032 -0.289072  ...  0.101428 -0.130816  0.129142   
gene2  -0.125624 -0.452441  0.065494  ... -0.063921  0.158165 -0.302828   
gene3   0.324254 -0.748180  0.015663  ... -1.328485 -0.194828  0.362047   
gene4   0.611454  0.376156  0.029306  ...  0.107450 -0.292311 -0.626240   
gene5   0.406734  0.218177  0.175707  ...  0.182165 -0.205287 -0.639710   
...          ...       ...       ...  ...       ...       ...       ...   
BRAT1  -0.010432 -0.299120  0.024199  ... -0.084588 -0.154024  0.066592   
AFF3   -0.231326 -0.225197  0.138000  ... -0.122220 -0.113323 -0.211457   
U2SURP  0.114996  0.211252 -0.055827  ... -0.170706 -0.158339  0.146913   
ZMAT2  -0.023604 -0.033867  0.160862  ...  0.082234  0.235284  0.529912   
MS4A13 -0.091959 -0.163776 -0.103803  ... -0.036812  0.199203  0.068985   

         gene213   gene214   gene215   gene217   gene218   gene220   gene221  
gene1   0.164773  0.222201  0.106131 -0.180773 -0.012366 -0.009747 -0.154899  
gene2  -0.320000 -0.031677  0.395132  0.123037  0.110232  0.101665  0.257199  
gene3   0.585154  0.141589  0.017662  0.035308 -0.128555  0.034865  0.047448  
gene4  -0.073600 -0.394079  0.076723  0.053355 -0.083475  0.497633  0.043747  
gene5   0.003630 -0.512942  0.184551 -0.068344  0.164594  0.551412  0.173682  
...          ...       ...       ...       ...       ...       ...       ...  
BRAT1   0.497428 -0.372607 -1.328724  0.006734  0.272284  0.139901  0.350091  
AFF3   -0.055832 -0.345783 -0.180888  0.133308 -0.340802 -0.299686  0.111915  
U2SURP  0.128541  0.005456  0.091263 -0.095923 -0.012799  0.065157  0.386429  
ZMAT2   0.153064 -0.215954 -0.216660  0.045671  0.104535  0.057949  0.035097  
MS4A13  0.270296 -0.119894 -0.275503  0.233243  0.181788  0.114834 -0.056764  

[17804 rows x 181 columns]

In [25]:
# [[1][2][3]] : 3 sample

In [26]:
#if need Standard Scaler 

# from sklearn.preprocessing import StandardScaler
# transfer= StandardScaler()
# train_input1=transfer.fit_transform(train_input).T
# train_output1=transfer.transform(train_output).T

In [27]:
# if not need

train_input1=train_input.T
train_output1=train_output.T

In [28]:
train_input1.shape

(181, 181)

In [29]:
train_output1.shape

(181, 17804)

In [30]:
# every row, like gene2 (1 X 181)
train_input.T

array([[ 0.06583944, -0.11888742, -0.00575577, ...,  0.11023176,
         0.1016647 ,  0.2571986 ],
       [ 0.02952638,  0.98498897, -0.49199274, ..., -0.08347453,
         0.49763344,  0.04374663],
       [ 0.03363636, -2.16797019,  0.6334151 , ...,  0.16459392,
         0.5514122 ,  0.17368199],
       ...,
       [-0.32266876, -0.30860534,  0.04768813, ...,  0.47418673,
         0.07410606, -0.22005477],
       [-0.05263766, -0.17790281, -0.04928005, ..., -0.05069485,
         0.29760144, -0.89152526],
       [-0.06734736,  0.37720076, -0.32043717, ...,  0.56297747,
        -0.31119432,  0.92373218]])

In [31]:
df_select

gene2     gene4     gene5     gene6     gene7     gene9    gene10  \
gene2    0.065839 -0.118887 -0.005756  0.023376 -0.029996 -0.223476 -0.528847   
gene4    0.029526  0.984989 -0.491993 -0.823344 -0.234515  0.036838  0.483608   
gene5    0.033636 -2.167970  0.633415 -0.482965 -0.192736  0.210778  0.301757   
gene6    0.108013 -0.328879  0.162317  0.431703 -0.086004 -0.129172 -0.092746   
gene7    0.019646 -0.371370  0.071836 -0.041403  0.512223 -0.223488  0.350104   
...           ...       ...       ...       ...       ...       ...       ...   
gene215 -0.463643  0.082758  0.317132  0.161844 -0.036863 -0.002925  0.029971   
gene217  0.418748 -0.058076 -0.136244  0.109349  0.146626 -0.382758 -0.074248   
gene218 -0.322669 -0.308605  0.047688  0.051777 -0.029663 -0.385610 -0.204980   
gene220 -0.052638 -0.177903 -0.049280  0.047704  0.515500  0.101023  0.251072   
gene221 -0.067347  0.377201 -0.320437  0.229495 -0.070635  0.085685 -0.010330   

           gene11    gene12    gene14  ...   gene210   gene211   gene212  \
gene2   -0.125624 -0.452441  0.065494  ... -0.063921  0.158165 -0.302828   
gene4    0.611454  0.376156  0.029306  ...  0.107450 -0.292311 -0.626240   
gene5    0.406734  0.218177  0.175707  ...  0.182165 -0.205287 -0.639710   
gene6   -0.037032 -0.091183 -0.183854  ...  0.098941 -0.002686  0.305216   
gene7    0.130423  0.744391  0.305899  ... -0.007832 -0.043968 -0.024252   
...           ...       ...       ...  ...       ...       ...       ...   
gene215  0.016223 -0.397910  0.217715  ... -0.161846 -0.314271  0.139246   
gene217  0.100994 -0.042505 -0.082459  ... -0.118175 -0.271400  0.276619   
gene218  0.236129 -0.012021  0.031613  ... -0.067217  0.039918 -0.096817   
gene220 -0.123151 -0.344285 -0.186162  ...  0.055105  0.447805 -0.120764   
gene221  0.026625 -0.749728 -0.353951  ...  0.181114  0.050261 -0.602545   

          gene213   gene214   gene215   gene217   gene218   gene220   gene221  
gene2   -0.320000 -0.031677  0.395132  0.123037  0.110232  0.101665  0.257199  
gene4   -0.073600 -0.394079  0.076723  0.053355 -0.083475  0.497633  0.043747  
gene5    0.003630 -0.512942  0.184551 -0.068344  0.164594  0.551412  0.173682  
gene6   -0.218668 -0.199505  0.113797  0.010453 -0.072276 -0.210557  0.128117  
gene7   -0.273954 -0.113345  0.019182  0.158748 -0.145833 -0.147716  0.057948  
...           ...       ...       ...       ...       ...       ...       ...  
gene215  0.312857 -0.430084 -0.484038 -0.432958 -0.339392 -0.133166  0.076858  
gene217 -0.032658  0.130579 -0.246864  0.236280 -0.121157 -0.063129  0.108336  
gene218  0.014080 -0.098842 -0.391419  0.145380  0.474187  0.074106 -0.220055  
gene220  0.383497  0.340230 -0.265943 -0.169058 -0.050695  0.297601 -0.891525  
gene221 -0.635713  0.501333  0.116678  0.007682  0.562977 -0.311194  0.923732  

[181 rows x 181 columns]

In [32]:
train_output1.shape

(181, 17804)

In [33]:
# each column, like gene2 [17k X 1] features
train_output.T

array([[-0.11226395,  0.06583944, -0.18229499, ..., -0.05281078,
        -0.05441056, -0.1327504 ],
       [-0.08251952, -0.11888742,  0.02528693, ...,  0.3747446 ,
         0.22339379,  0.13308728],
       [-0.02313652, -0.00575577,  0.0850271 , ...,  0.08258123,
        -0.13230597, -0.03239652],
       ...,
       [-0.01236593,  0.11023176, -0.12855512, ..., -0.0127993 ,
         0.10453501,  0.18178788],
       [-0.00974718,  0.1016647 ,  0.03486457, ...,  0.06515736,
         0.05794941,  0.11483372],
       [-0.15489869,  0.2571986 ,  0.04744789, ...,  0.38642932,
         0.03509739, -0.05676414]])

In [34]:
train_input1

array([[ 0.06583944, -0.11888742, -0.00575577, ...,  0.11023176,
         0.1016647 ,  0.2571986 ],
       [ 0.02952638,  0.98498897, -0.49199274, ..., -0.08347453,
         0.49763344,  0.04374663],
       [ 0.03363636, -2.16797019,  0.6334151 , ...,  0.16459392,
         0.5514122 ,  0.17368199],
       ...,
       [-0.32266876, -0.30860534,  0.04768813, ...,  0.47418673,
         0.07410606, -0.22005477],
       [-0.05263766, -0.17790281, -0.04928005, ..., -0.05069485,
         0.29760144, -0.89152526],
       [-0.06734736,  0.37720076, -0.32043717, ...,  0.56297747,
        -0.31119432,  0.92373218]])

In [35]:
train_output1.shape

(181, 17804)

In [36]:
train_output1

array([[-0.11226395,  0.06583944, -0.18229499, ..., -0.05281078,
        -0.05441056, -0.1327504 ],
       [-0.08251952, -0.11888742,  0.02528693, ...,  0.3747446 ,
         0.22339379,  0.13308728],
       [-0.02313652, -0.00575577,  0.0850271 , ...,  0.08258123,
        -0.13230597, -0.03239652],
       ...,
       [-0.01236593,  0.11023176, -0.12855512, ..., -0.0127993 ,
         0.10453501,  0.18178788],
       [-0.00974718,  0.1016647 ,  0.03486457, ...,  0.06515736,
         0.05794941,  0.11483372],
       [-0.15489869,  0.2571986 ,  0.04744789, ...,  0.38642932,
         0.03509739, -0.05676414]])

In [37]:
# for Neural network testing: 

# from sklearn.neural_network import MLPRegressor
# from sklearn.model_selection import GridSearchCV

# model = MLPRegressor(solver='sgd', activation='relu', max_iter=2000,alpha=0.001,tol=1e-5)

# param_grid = {'hidden_layer_sizes': [(1000,2000,2000,3000),(1000,500,500,500,600), (1000,500,500,500)],
#              }

# grid = GridSearchCV(model, param_grid, cv=3,verbose=3)
# grid.fit(train_input1, train_output1)
# print(grid.best_params_)
# print(grid.best_score_)

In [38]:
from sklearn.neural_network import MLPRegressor
model = MLPRegressor(solver='sgd',activation='relu',hidden_layer_sizes=(1000, 500, 500, 500), max_iter=2000, tol=1e-4)

model.fit(train_input1, train_output1)

MLPRegressor(hidden_layer_sizes=(1000, 500, 500, 500), max_iter=2000,
             solver='sgd')

In [39]:
# from sklearn.model_selection import cross_val_score

# scores = cross_val_score(model, train_input1, train_output1, cv=5, scoring='neg_mean_squared_error')
# scores = -scores
# print("Mean Squared Error: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))


In [40]:
# Method 2---random forest

# BootStrap: 

# from sklearn.ensemble import RandomForestRegressor
# from sklearn.model_selection import GridSearchCV

# model = RandomForestRegressor()
# param_dict = {"n_estimators": [120, 200, 300, 500,800], "max_depth": [5, 8, 15, 25],"max_features":["sqrt"]}

# model = GridSearchCV(model, param_grid=param_dict, cv=2,verbose=3)



In [41]:
# model.fit(train_input1, train_output1)

In [42]:
test_input = test_input.reshape(1, 181)

In [43]:
predicted_value = model.predict(test_input)
predicted_value

array([[ 0.01225078,  0.00215868,  0.00728383, ...,  0.023142  ,
        -0.02176861,  0.01537672]])

In [44]:
test_output

array([-0.15489869,  0.2571986 ,  0.04744789, ...,  0.38642932,
        0.03509739, -0.05676414])

In [45]:
gene194= df.loc["gene194"].to_numpy()

In [46]:
predicted_value = model.predict(gene194.reshape(1, 181))
predicted_value 

array([[ 0.00445981,  0.01135288, -0.01100395, ...,  0.01086982,
        -0.00990904,  0.01251093]])

In [47]:
predict=pd.DataFrame(columns=["gene194"],data=predicted_value.T)


In [48]:
test_genes=test_genes.tolist()
test_genes.remove('gene194')

In [49]:
for index,row in df.iterrows():
    if index in test_genes:
            curr_gene= df.loc[index].to_numpy()
            predicted_value = model.predict(curr_gene.reshape(1, 181))
            curr_predict_column=pd.DataFrame(columns=[index],data=predicted_value.T)
            predict = pd.concat([predict, curr_predict_column], axis=1)
            
predict

gene194     gene1     gene3     gene8    gene13    gene16    gene20  \
0      0.004460  0.003051 -0.010381  0.002928 -0.004424 -0.000907 -0.003852   
1      0.011353  0.000857  0.010048  0.006131  0.000203 -0.004421  0.016382   
2     -0.011004 -0.010385 -0.014504 -0.005846 -0.012243 -0.008433 -0.006119   
3     -0.015628 -0.009779 -0.021645 -0.011209 -0.016589 -0.012166 -0.011543   
4     -0.003496 -0.002958 -0.001154 -0.003549 -0.002584 -0.000634 -0.008279   
...         ...       ...       ...       ...       ...       ...       ...   
17799  0.024256  0.007314  0.012918  0.018512  0.016093  0.007562  0.021451   
17800  0.005600  0.019449  0.003898  0.000983  0.008657  0.007339  0.013533   
17801  0.010870  0.021686  0.023682  0.009254  0.016064  0.015004  0.012414   
17802 -0.009909 -0.014306 -0.031672 -0.014989 -0.018052 -0.024290 -0.022967   
17803  0.012511  0.012506  0.027725  0.013242  0.018760  0.013785  0.012677   

         gene21    gene23    gene25  ...   gene183   gene184   gene186  \
0     -0.004161 -0.002762 -0.004019  ...  0.002958  0.001939 -0.002517   
1     -0.000227  0.003141 -0.001166  ...  0.012314  0.008495  0.002622   
2     -0.016147 -0.013873 -0.011083  ... -0.008261 -0.012218 -0.015106   
3     -0.024576 -0.012322 -0.018317  ... -0.010211 -0.003484 -0.015112   
4      0.001564  0.001275  0.000902  ...  0.008504  0.001796 -0.006206   
...         ...       ...       ...  ...       ...       ...       ...   
17799  0.018604  0.021110  0.013829  ...  0.029807  0.012774  0.017549   
17800  0.001949  0.010724  0.005438  ...  0.007656  0.013806  0.012440   
17801  0.019493  0.015467  0.020531  ... -0.003591  0.012689  0.016660   
17802 -0.018645 -0.012318 -0.017548  ... -0.014937 -0.023535 -0.019727   
17803  0.013889  0.018284  0.022409  ...  0.017932  0.019087  0.015056   

        gene187   gene189   gene192   gene206   gene207   gene216   gene219  
0      0.000628 -0.008731 -0.004849  0.001475  0.004866 -0.009125 -0.000632  
1      0.002264 -0.006645  0.006735  0.001443 -0.000496 -0.005403 -0.000232  
2     -0.004672 -0.009701 -0.011585 -0.006118  0.000009 -0.011416 -0.014216  
3     -0.014134 -0.011211 -0.009905 -0.008389 -0.014975 -0.016090 -0.013166  
4      0.002829 -0.000696  0.004860 -0.004730 -0.004111  0.002486 -0.002433  
...         ...       ...       ...       ...       ...       ...       ...  
17799  0.015355  0.018022  0.019963  0.015743  0.012092  0.014349  0.021313  
17800  0.009299  0.010354  0.011277  0.012437  0.004926  0.012322  0.011075  
17801  0.015146  0.007567  0.012299  0.006096  0.004729  0.013525  0.009985  
17802 -0.017868 -0.019281 -0.011074 -0.018961 -0.021021 -0.031454 -0.021241  
17803  0.014846  0.021571  0.010678  0.014296  0.014463  0.012869  0.014877  

[17804 rows x 40 columns]

In [55]:
features_list=df.index.tolist()

In [56]:
predict = predict.set_index(pd.Index(features_list))
predict

gene58    gene83   gene189   gene184    gene98    gene33     gene1  \
gene1  -0.008446 -0.002054 -0.008731  0.001939 -0.009427 -0.000253  0.003051   
gene2   0.000121  0.001921 -0.006645  0.008495 -0.000152  0.003305  0.000857   
gene3  -0.012949 -0.018167 -0.009701 -0.012218 -0.017779  0.003412 -0.010385   
gene4  -0.019771 -0.016911 -0.011211 -0.003484 -0.015983 -0.007604 -0.009779   
gene5  -0.003791 -0.002372 -0.000696  0.001796 -0.001799 -0.005074 -0.002958   
...          ...       ...       ...       ...       ...       ...       ...   
BRAT1   0.017940  0.020830  0.018022  0.012774  0.023838  0.027057  0.007314   
AFF3    0.016739  0.006818  0.010354  0.013806  0.008955 -0.006737  0.019449   
U2SURP  0.016646  0.017021  0.007567  0.012689  0.014775  0.000979  0.021686   
ZMAT2  -0.017672 -0.017136 -0.019281 -0.023535 -0.029350 -0.015010 -0.014306   
MS4A13  0.016632  0.015113  0.021571  0.019087  0.018982  0.025407  0.012506   

         gene139    gene55    gene23    gene49    gene25    gene61   gene160  \
gene1  -0.009890 -0.001427 -0.002762 -0.004603 -0.004019  0.001681  0.008438   
gene2   0.005350  0.004101  0.003141 -0.002093 -0.001166  0.007951 -0.000557   
gene3  -0.008929 -0.014008 -0.013873 -0.009457 -0.011083 -0.005782  0.008057   
gene4  -0.011796 -0.017572 -0.012322 -0.016156 -0.018317 -0.008869 -0.004264   
gene5  -0.002265  0.000859  0.001275 -0.003509  0.000902 -0.003255  0.006471   
...          ...       ...       ...       ...       ...       ...       ...   
BRAT1   0.018832  0.014202  0.021110  0.019762  0.013829  0.023988  0.014342   
AFF3    0.007646  0.007482  0.010724  0.007155  0.005438  0.003036  0.002531   
U2SURP  0.008916  0.010254  0.015467  0.013508  0.020531  0.006984  0.003016   
ZMAT2  -0.011943 -0.026916 -0.012318 -0.016454 -0.017548 -0.013175 -0.027205   
MS4A13  0.025592  0.027109  0.018284  0.017316  0.022409  0.014805  0.026675   

         gene194   gene179   gene216   gene127   gene206    gene13  
gene1   0.004460 -0.003047 -0.009125 -0.009489  0.001475 -0.004424  
gene2   0.011353 -0.002440 -0.005403  0.008388  0.001443  0.000203  
gene3  -0.011004 -0.015129 -0.011416 -0.011631 -0.006118 -0.012243  
gene4  -0.015628 -0.010279 -0.016090 -0.017639 -0.008389 -0.016589  
gene5  -0.003496 -0.005223  0.002486 -0.006434 -0.004730 -0.002584  
...          ...       ...       ...       ...       ...       ...  
BRAT1   0.024256  0.023982  0.014349  0.014615  0.015743  0.016093  
AFF3    0.005600  0.010765  0.012322  0.007943  0.012437  0.008657  
U2SURP  0.010870  0.013152  0.013525  0.003611  0.006096  0.016064  
ZMAT2  -0.009909 -0.014288 -0.031454 -0.036619 -0.018961 -0.018052  
MS4A13  0.012511  0.019980  0.012869  0.023200  0.014296  0.018760  

[17804 rows x 20 columns]

In [57]:
list_20=["gene58","gene83","gene189","gene184","gene98","gene33","gene1","gene139","gene55","gene23","gene49","gene25","gene61","gene160","gene194","gene179","gene216","gene127","gene206","gene13"]
list_20
predict = predict.reindex(columns=list_20)

In [58]:
predict

gene58    gene83   gene189   gene184    gene98    gene33     gene1  \
gene1  -0.008446 -0.002054 -0.008731  0.001939 -0.009427 -0.000253  0.003051   
gene2   0.000121  0.001921 -0.006645  0.008495 -0.000152  0.003305  0.000857   
gene3  -0.012949 -0.018167 -0.009701 -0.012218 -0.017779  0.003412 -0.010385   
gene4  -0.019771 -0.016911 -0.011211 -0.003484 -0.015983 -0.007604 -0.009779   
gene5  -0.003791 -0.002372 -0.000696  0.001796 -0.001799 -0.005074 -0.002958   
...          ...       ...       ...       ...       ...       ...       ...   
BRAT1   0.017940  0.020830  0.018022  0.012774  0.023838  0.027057  0.007314   
AFF3    0.016739  0.006818  0.010354  0.013806  0.008955 -0.006737  0.019449   
U2SURP  0.016646  0.017021  0.007567  0.012689  0.014775  0.000979  0.021686   
ZMAT2  -0.017672 -0.017136 -0.019281 -0.023535 -0.029350 -0.015010 -0.014306   
MS4A13  0.016632  0.015113  0.021571  0.019087  0.018982  0.025407  0.012506   

         gene139    gene55    gene23    gene49    gene25    gene61   gene160  \
gene1  -0.009890 -0.001427 -0.002762 -0.004603 -0.004019  0.001681  0.008438   
gene2   0.005350  0.004101  0.003141 -0.002093 -0.001166  0.007951 -0.000557   
gene3  -0.008929 -0.014008 -0.013873 -0.009457 -0.011083 -0.005782  0.008057   
gene4  -0.011796 -0.017572 -0.012322 -0.016156 -0.018317 -0.008869 -0.004264   
gene5  -0.002265  0.000859  0.001275 -0.003509  0.000902 -0.003255  0.006471   
...          ...       ...       ...       ...       ...       ...       ...   
BRAT1   0.018832  0.014202  0.021110  0.019762  0.013829  0.023988  0.014342   
AFF3    0.007646  0.007482  0.010724  0.007155  0.005438  0.003036  0.002531   
U2SURP  0.008916  0.010254  0.015467  0.013508  0.020531  0.006984  0.003016   
ZMAT2  -0.011943 -0.026916 -0.012318 -0.016454 -0.017548 -0.013175 -0.027205   
MS4A13  0.025592  0.027109  0.018284  0.017316  0.022409  0.014805  0.026675   

         gene194   gene179   gene216   gene127   gene206    gene13  
gene1   0.004460 -0.003047 -0.009125 -0.009489  0.001475 -0.004424  
gene2   0.011353 -0.002440 -0.005403  0.008388  0.001443  0.000203  
gene3  -0.011004 -0.015129 -0.011416 -0.011631 -0.006118 -0.012243  
gene4  -0.015628 -0.010279 -0.016090 -0.017639 -0.008389 -0.016589  
gene5  -0.003496 -0.005223  0.002486 -0.006434 -0.004730 -0.002584  
...          ...       ...       ...       ...       ...       ...  
BRAT1   0.024256  0.023982  0.014349  0.014615  0.015743  0.016093  
AFF3    0.005600  0.010765  0.012322  0.007943  0.012437  0.008657  
U2SURP  0.010870  0.013152  0.013525  0.003611  0.006096  0.016064  
ZMAT2  -0.009909 -0.014288 -0.031454 -0.036619 -0.018961 -0.018052  
MS4A13  0.012511  0.019980  0.012869  0.023200  0.014296  0.018760  

[17804 rows x 20 columns]

In [59]:
predict.to_csv('mydata.csv', index=True)